{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "rCKx9GrYQrxJ"
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "UsageError: Line magic function `%tensorflow_version` not found.\n"
     ]
    }
   ],
   "source": [
    "%tensorflow_version 1.x\n",
    "from skimage import measure, transform\n",
    "import matplotlib.pyplot as plt\n",
    "from keras import backend as K\n",
    "import nibabel as nib\n",
    "import numpy as np\n",
    "import glob\n",
    "import math\n",
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 122
    },
    "colab_type": "code",
    "id": "AAxCh6cqQziX",
    "outputId": "111dc632-b6a3-4188-9bff-a120063768bf"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly\n",
      "\n",
      "Enter your authorization code:\n",
      "··········\n",
      "Mounted at /content/drive\n"
     ]
    }
   ],
   "source": [
    "from google.colab import drive\n",
    "drive.mount('/content/drive')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "t-UdhMkeTPDX"
   },
   "outputs": [],
   "source": [
    "def fft_lr(img, factor):\n",
    "    x = int(img.shape[1]//(factor*2))\n",
    "    imgfft = np.fft.fftn(img)\n",
    "    imgfft = np.fft.fftshift(imgfft)\n",
    "    y_center = imgfft.shape[1] // 2\n",
    "    z_center = imgfft.shape[2] // 2\n",
    "    imgfft = imgfft[:, y_center-x : y_center+x, z_center-x : z_center+x]\n",
    "    imgifft = np.fft.ifftn(imgfft)\n",
    "    lr_img = abs(imgifft)\n",
    "\n",
    "    lr_img = transform.resize(lr_img, img.shape)\n",
    "    lr_img /= lr_img.max()\n",
    "    lr_img *= 255\n",
    "    return lr_img"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "TWCglwfHQ15e"
   },
   "outputs": [],
   "source": [
    "def PSNR(y_true, y_pred):\n",
    "    max_pixel = 255.0\n",
    "    return 10.0 * (1.0 / math.log(10)) * K.log((max_pixel ** 2) / (K.mean(K.square(y_pred - y_true))))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "qQNa9qvKQ4WG"
   },
   "outputs": [],
   "source": [
    "def psnr(y_true, y_pred):\n",
    "    # y_true = y_true.astype(np.float64) / 255.\n",
    "    # y_pred = y_pred.astype(np.float64) / 255.\n",
    "    mse = np.mean( (y_true - y_pred) ** 2 )\n",
    "    if mse == 0:\n",
    "      return 100\n",
    "    return 20 * math.log10(255 / math.sqrt(mse))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "jhl6L_luQ6YO",
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Using TensorFlow backend.\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-5-623ae21f8c21>\", line 2, in <module>\n",
      "    m2d = load_model('/content/drive/My Drive/Colab Notebooks/final/model_2d_fft.h5')\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\keras\\models.py\", line 237, in load_model\n",
      "    with h5py.File(filepath, mode='r') as f:\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\h5py\\_hl\\files.py\", line 445, in __init__\n",
      "    swmr=swmr)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\h5py\\_hl\\files.py\", line 195, in make_fid\n",
      "    fid = h5f.open(name, flags, fapl=fapl)\n",
      "  File \"h5py\\_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py\\_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py\\h5f.pyx\", line 96, in h5py.h5f.open\n",
      "FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/content/drive/My Drive/Colab Notebooks/final/model_2d_fft.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\tensorflow_core\\contrib\\__init__.py\", line 39, in <module>\n",
      "    from tensorflow.contrib import compiler\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\tensorflow_core\\contrib\\compiler\\__init__.py\", line 21, in <module>\n",
      "    from tensorflow.contrib.compiler import jit\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\tensorflow_core\\contrib\\compiler\\__init__.py\", line 22, in <module>\n",
      "    from tensorflow.contrib.compiler import xla\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\tensorflow_core\\contrib\\compiler\\xla.py\", line 22, in <module>\n",
      "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\tensorflow_core\\python\\estimator\\model_fn.py\", line 26, in <module>\n",
      "    from tensorflow_estimator.python.estimator import model_fn\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\model_fn.py\", line 29, in <module>\n",
      "    from tensorflow.python.types import core\n",
      "ModuleNotFoundError: No module named 'tensorflow.python.types'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-5-623ae21f8c21>\", line 2, in <module>\n",
      "    m2d = load_model('/content/drive/My Drive/Colab Notebooks/final/model_2d_fft.h5')\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\keras\\models.py\", line 237, in load_model\n",
      "    with h5py.File(filepath, mode='r') as f:\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\h5py\\_hl\\files.py\", line 445, in __init__\n",
      "    swmr=swmr)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\h5py\\_hl\\files.py\", line 195, in make_fid\n",
      "    fid = h5f.open(name, flags, fapl=fapl)\n",
      "  File \"h5py\\_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py\\_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py\\h5f.pyx\", line 96, in h5py.h5f.open\n",
      "FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/content/drive/My Drive/Colab Notebooks/final/model_2d_fft.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3454, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-5-623ae21f8c21>\", line 2, in <module>\n",
      "    m2d = load_model('/content/drive/My Drive/Colab Notebooks/final/model_2d_fft.h5')\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\keras\\models.py\", line 237, in load_model\n",
      "    with h5py.File(filepath, mode='r') as f:\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\h5py\\_hl\\files.py\", line 445, in __init__\n",
      "    swmr=swmr)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\h5py\\_hl\\files.py\", line 195, in make_fid\n",
      "    fid = h5f.open(name, flags, fapl=fapl)\n",
      "  File \"h5py\\_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py\\_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py\\h5f.pyx\", line 96, in h5py.h5f.open\n",
      "FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/content/drive/My Drive/Colab Notebooks/final/model_2d_fft.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3454, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3166, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3376, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1143, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\user\\anaconda3\\envs\\gputest\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    }
   ],
   "source": [
    "from keras.models import load_model\n",
    "m2d = load_model('/content/drive/My Drive/Colab Notebooks/final/model_2d_fft.h5')\n",
    "m3d = load_model('/content/drive/My Drive/Colab Notebooks/final/model_3d_915_32x32.h5')\n",
    "m3df = load_model('/content/drive/My Drive/Colab Notebooks/final/fsrcnn_56_16_relu_2.h5', custom_objects={'PSNR': PSNR})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "uMybLnL6TG0x"
   },
   "outputs": [],
   "source": [
    "files = (glob.glob(\"/content/drive/My Drive/scanss/*.nii.gz\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 309
    },
    "colab_type": "code",
    "id": "ptTsgGarSemY",
    "outputId": "d42de4b6-6d6a-4013-b08d-522eb9fa0140"
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:27: UserWarning: DEPRECATED: skimage.measure.compare_ssim has been moved to skimage.metrics.structural_similarity. It will be removed from skimage.measure in version 0.18.\n",
      "/usr/local/lib/python3.6/dist-packages/skimage/measure/_structural_similarity.py:17: UserWarning: Inputs have mismatched dtype.  Setting data_range based on im1.dtype.\n",
      "  **kwargs)\n",
      "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:46: UserWarning: DEPRECATED: skimage.measure.compare_ssim has been moved to skimage.metrics.structural_similarity. It will be removed from skimage.measure in version 0.18.\n",
      "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:65: UserWarning: DEPRECATED: skimage.measure.compare_ssim has been moved to skimage.metrics.structural_similarity. It will be removed from skimage.measure in version 0.18.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Max PSNR(2DSRCNN): 37.155619744747895\n",
      "Average PSNR(2DSRCNN): 32.49401813642935\n",
      "Min PSNR(2DSRCNN): 24.97284103292985\n",
      "\n",
      "Max SSIM(2DSRCNN): 0.9844260463489186\n",
      "Average SSIM(2DSRCNN): 0.8608954532266173\n",
      "Min SSIM(2DSRCNN): 0.8102512056702726\n",
      "\n",
      "Average time(second) for each scan: 3.1840524514516195\n",
      "\n"
     ]
    }
   ],
   "source": [
    "#for 2dsrcnn\n",
    "timez = 0\n",
    "p = 35\n",
    "s = 0.95\n",
    "maxp = 0\n",
    "minp = 100\n",
    "maxs = 0\n",
    "mins = 100\n",
    "for image in range (len(files)):\n",
    "    start_time = time.time()\n",
    "    img = nib.load(files[image])\n",
    "    img_data = img.get_fdata()\n",
    "    img_data = img_data/(np.amax(img_data))\n",
    "    img_data = img_data * 255\n",
    "    hr = np.array(img_data, dtype='uint8')\n",
    "\n",
    "    lr = fft_lr(hr, 2)\n",
    "    lr = np.array(lr, dtype='uint8')\n",
    "    for x in range(hr.shape[0]):\n",
    "        hr1 = hr[x,:,:]\n",
    "        lr1 = lr[x,:,:]\n",
    "        lr1_1 = np.reshape(lr1, (1, hr1.shape[0], hr1.shape[1], 1))\n",
    "\n",
    "        sr1 = m2d.predict(lr1_1)\n",
    "        sr1 = np.reshape(sr1,hr1.shape)\n",
    "        p = (p + psnr(hr1, sr1))/2\n",
    "        s0, d = measure.compare_ssim(hr1, sr1, full=True)\n",
    "        s = (s + s0)/2\n",
    "        if p > maxp:\n",
    "            maxp = p\n",
    "        if p < minp:\n",
    "            minp = p\n",
    "        if s > maxs:\n",
    "            maxs = s\n",
    "        if s < mins:\n",
    "            mins = s\n",
    "\n",
    "    for y in range(hr.shape[1]):\n",
    "        hr1 = hr[:,y,:]\n",
    "        lr1 = lr[:,y,:]\n",
    "        lr1_1 = np.reshape(lr1, (1, hr1.shape[0], hr1.shape[1], 1))\n",
    "\n",
    "        sr1 = m2d.predict(lr1_1)\n",
    "        sr1 = np.reshape(sr1,hr1.shape)\n",
    "        p = (p + psnr(hr1, sr1))/2\n",
    "        s0, d = measure.compare_ssim(hr1, sr1, full=True)\n",
    "        s = (s + s0)/2\n",
    "        if p > maxp:\n",
    "            maxp = p\n",
    "        if p < minp:\n",
    "            minp = p\n",
    "        if s > maxs:\n",
    "            maxs = s\n",
    "        if s < mins:\n",
    "            mins = s\n",
    "\n",
    "    for z in range(hr.shape[2]):\n",
    "        hr1 = hr[:,:,z]\n",
    "        lr1 = lr[:,:,z]\n",
    "        lr1_1 = np.reshape(lr1, (1, hr1.shape[0], hr1.shape[1], 1))\n",
    "\n",
    "        sr1 = m2d.predict(lr1_1)\n",
    "        sr1 = np.reshape(sr1,hr1.shape)\n",
    "        p = (p + psnr(hr1, sr1))/2\n",
    "        s0, d = measure.compare_ssim(hr1, sr1, full=True)\n",
    "        s = (s + s0)/2\n",
    "        if p > maxp:\n",
    "            maxp = p\n",
    "        if p < minp:\n",
    "            minp = p\n",
    "        if s > maxs:\n",
    "            maxs = s\n",
    "        if s < mins:\n",
    "            mins = s\n",
    "\n",
    "    timez += (time.time() - start_time)\n",
    "\n",
    "print()\n",
    "print(\"Max PSNR(2DSRCNN):\", maxp)\n",
    "print(\"Average PSNR(2DSRCNN):\", p)\n",
    "print(\"Min PSNR(2DSRCNN):\", minp)\n",
    "print()\n",
    "print(\"Max SSIM(2DSRCNN):\", maxs)\n",
    "print(\"Average SSIM(2DSRCNN):\", s)\n",
    "print(\"Min SSIM(2DSRCNN):\", mins)\n",
    "print()\n",
    "print(\"Average time(second) for each scan:\", timez/len(files))\n",
    "print()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 275
    },
    "colab_type": "code",
    "id": "viFeI0uCgScY",
    "outputId": "6ac95f17-201d-4a84-a3a3-44d35f9d60fa"
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:36: UserWarning: DEPRECATED: skimage.measure.compare_ssim has been moved to skimage.metrics.structural_similarity. It will be removed from skimage.measure in version 0.18.\n",
      "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:52: UserWarning: DEPRECATED: skimage.measure.compare_ssim has been moved to skimage.metrics.structural_similarity. It will be removed from skimage.measure in version 0.18.\n",
      "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:68: UserWarning: DEPRECATED: skimage.measure.compare_ssim has been moved to skimage.metrics.structural_similarity. It will be removed from skimage.measure in version 0.18.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Max PSNR(3DSRCNN): 41.22989450492577\n",
      "Average PSNR(3DSRCNN): 35.253762055833256\n",
      "Min PSNR(3DSRCNN): 29.290997790650188\n",
      "\n",
      "Max SSIM(3DSRCNN): 0.976620152412472\n",
      "Average SSIM(3DSRCNN): 0.904876076269809\n",
      "Min SSIM(3DSRCNN): 0.7497611097528034\n",
      "\n",
      "Average time(second) for each scan: 11.454299628734589\n",
      "\n"
     ]
    }
   ],
   "source": [
    "#for 3dsrcnn\n",
    "timez = 0\n",
    "p = 35\n",
    "s = 0.95\n",
    "maxp = 0\n",
    "minp = 100\n",
    "maxs = 0\n",
    "mins = 100\n",
    "for image in range (len(files)):\n",
    "    start_time = time.time()\n",
    "    img = nib.load(files[image])\n",
    "    img_data = img.get_fdata()\n",
    "    img_data = img_data/(np.amax(img_data))\n",
    "    img_data = img_data * 255\n",
    "    hr = np.array(img_data, dtype='uint8')\n",
    "\n",
    "    test_lr = fft_lr(hr, 2.5)\n",
    "    test_lr = np.array(test_lr, dtype='uint8')\n",
    "    test_sr = np.ndarray((256, 320, 320), dtype='uint8')\n",
    "\n",
    "    for i in range(0, 256, 64):\n",
    "        for j in range(0, 320, 64):\n",
    "            for k in range(0, 320, 64):\n",
    "                lrx = test_lr[i:i+64, j:j+64, k:k+64]\n",
    "                lrx = np.reshape(lrx, (1, lrx.shape[0], lrx.shape[1], lrx.shape[2], 1))\n",
    "                srx = m3d.predict(lrx)\n",
    "                srx = np.reshape(srx, (64,64,64))\n",
    "                test_sr[i:i+64, j:j+64, k:k+64] = srx\n",
    "    timez += time.time() - start_time\n",
    "\n",
    "    for x in range(hr.shape[0]):\n",
    "        hr1 = hr[x,:,:]\n",
    "        sr1 = test_sr[x,:,:]\n",
    "\n",
    "        p = (p + psnr(hr1, sr1))/2\n",
    "        s0, d = measure.compare_ssim(hr1, sr1, full=True)\n",
    "        s = (s + s0)/2\n",
    "        if p > maxp:\n",
    "            maxp = p\n",
    "        if p < minp:\n",
    "            minp = p\n",
    "        if s > maxs:\n",
    "            maxs = s\n",
    "        if s < mins:\n",
    "            mins = s\n",
    "\n",
    "    for y in range(hr.shape[1]):\n",
    "        hr1 = hr[:,y,:]\n",
    "        sr1 = test_sr[:,y,:]\n",
    "\n",
    "        p = (p + psnr(hr1, sr1))/2\n",
    "        s0, d = measure.compare_ssim(hr1, sr1, full=True)\n",
    "        s = (s + s0)/2\n",
    "        if p > maxp:\n",
    "            maxp = p\n",
    "        if p < minp:\n",
    "            minp = p\n",
    "        if s > maxs:\n",
    "            maxs = s\n",
    "        if s < mins:\n",
    "            mins = s\n",
    "\n",
    "    for z in range(hr.shape[2]):\n",
    "        hr1 = hr[:,:,z]\n",
    "        sr1 = test_sr[:,:,z]\n",
    "\n",
    "        p = (p + psnr(hr1, sr1))/2\n",
    "        s0, d = measure.compare_ssim(hr1, sr1, full=True)\n",
    "        s = (s + s0)/2\n",
    "        if p > maxp:\n",
    "            maxp = p\n",
    "        if p < minp:\n",
    "            minp = p\n",
    "        if s > maxs:\n",
    "            maxs = s\n",
    "        if s < mins:\n",
    "            mins = s\n",
    "\n",
    "print()\n",
    "print(\"Max PSNR(3DSRCNN):\", maxp)\n",
    "print(\"Average PSNR(3DSRCNN):\", p)\n",
    "print(\"Min PSNR(3DSRCNN):\", minp)\n",
    "print()\n",
    "print(\"Max SSIM(3DSRCNN):\", maxs)\n",
    "print(\"Average SSIM(3DSRCNN):\", s)\n",
    "print(\"Min SSIM(3DSRCNN):\", mins)\n",
    "print()\n",
    "print(\"Average time(second) for each scan:\", timez/len(files))\n",
    "print()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 275
    },
    "colab_type": "code",
    "id": "t2SRi_OsgYt3",
    "outputId": "b4674853-848e-4611-e67f-9f25b16f0cd8"
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:55: UserWarning: DEPRECATED: skimage.measure.compare_ssim has been moved to skimage.metrics.structural_similarity. It will be removed from skimage.measure in version 0.18.\n",
      "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:71: UserWarning: DEPRECATED: skimage.measure.compare_ssim has been moved to skimage.metrics.structural_similarity. It will be removed from skimage.measure in version 0.18.\n",
      "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:87: UserWarning: DEPRECATED: skimage.measure.compare_ssim has been moved to skimage.metrics.structural_similarity. It will be removed from skimage.measure in version 0.18.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Max PSNR(3DFSRCNN): 48.66321216684466\n",
      "Average PSNR(3DFSRCNN): 38.756011903383595\n",
      "Min PSNR(3DFSRCNN): 34.47256423180401\n",
      "\n",
      "Max SSIM(3DFSRCNN): 0.9853241307472062\n",
      "Average SSIM(3DFSRCNN): 0.9812111155616676\n",
      "Min SSIM(3DFSRCNN): 0.8471021333569505\n",
      "\n",
      "Average time(second) for each scan: 1.9810153047243755\n",
      "\n"
     ]
    }
   ],
   "source": [
    "#for 3dfsrcnn\n",
    "timez = 0\n",
    "p = 35\n",
    "s= 0.95\n",
    "maxp = 0\n",
    "minp = 100\n",
    "maxs = 0\n",
    "mins = 100\n",
    "for image in range (len(files)):\n",
    "    start_time = time.time()\n",
    "    img = nib.load(files[image])\n",
    "    img_data = img.get_fdata()\n",
    "    img_data = img_data/(np.amax(img_data))\n",
    "    img_data = img_data * 255\n",
    "    hr = np.array(img_data, dtype='uint8')\n",
    "\n",
    "    lr = hr[::2, ::2, ::2]\n",
    "    sr = np.zeros((256, 320, 320), dtype='uint8')\n",
    "    x = 0\n",
    "    x1 = 0\n",
    "    y = 0\n",
    "    y1 = 0\n",
    "    z = 0\n",
    "    z1 = 0\n",
    "\n",
    "    for i in range(4):\n",
    "        y = 0\n",
    "        y1 = 0\n",
    "        for j in range(5):\n",
    "            z = 0\n",
    "            z1 = 0\n",
    "            for k in range(5):\n",
    "                lr0 = np.zeros((1, 32, 32, 32), dtype='uint8')\n",
    "                lr0[0] = lr[x:x+32, y:y+32, z:z+32]\n",
    "                lr0.shape = lr0.shape + (1,)\n",
    "                sr0 = m3df.predict(lr0)\n",
    "\n",
    "                sr0 = np.reshape(sr0, (1,64,64,64))\n",
    "                sr[x1:x1+64, y1:y1+64, z1:z1+64] = sr0[0]\n",
    "\n",
    "                z = z + 32\n",
    "                z1 = z1 + 64\n",
    "            y = y + 32\n",
    "            y1 = y1 + 64\n",
    "        x = x + 32\n",
    "        x1 = x1 + 64\n",
    "\n",
    "    timez += time.time() - start_time\n",
    "\n",
    "    for x in range(hr.shape[0]):\n",
    "        hr1 = hr[x,:,:]\n",
    "        sr1 = sr[x,:,:]\n",
    "\n",
    "        p = (p + psnr(hr1, sr1))/2\n",
    "        s0, d = measure.compare_ssim(hr1, sr1, full=True)\n",
    "        s = (s + s0)/2\n",
    "        if p > maxp:\n",
    "            maxp = p\n",
    "        if p < minp:\n",
    "            minp = p\n",
    "        if s > maxs:\n",
    "            maxs = s\n",
    "        if s < mins:\n",
    "            mins = s\n",
    "\n",
    "    for y in range(hr.shape[1]):\n",
    "        hr1 = hr[:,y,:]\n",
    "        sr1 = sr[:,y,:]\n",
    "\n",
    "        p = (p + psnr(hr1, sr1))/2\n",
    "        s0, d = measure.compare_ssim(hr1, sr1, full=True)\n",
    "        s = (s + s0)/2\n",
    "        if p > maxp:\n",
    "            maxp = p\n",
    "        if p < minp:\n",
    "            minp = p\n",
    "        if s > maxs:\n",
    "            maxs = s\n",
    "        if s < mins:\n",
    "            mins = s\n",
    "\n",
    "    for z in range(hr.shape[2]):\n",
    "        hr1 = hr[:,:,z]\n",
    "        sr1 = sr[:,:,z]\n",
    "\n",
    "        p = (p + psnr(hr1, sr1))/2\n",
    "        s0, d = measure.compare_ssim(hr1, sr1, full=True)\n",
    "        s = (s + s0)/2\n",
    "        if p > maxp:\n",
    "            maxp = p\n",
    "        if p < minp:\n",
    "            minp = p\n",
    "        if s > maxs:\n",
    "            maxs = s\n",
    "        if s < mins:\n",
    "            mins = s\n",
    "\n",
    "print()\n",
    "print(\"Max PSNR(3DFSRCNN):\", maxp)\n",
    "print(\"Average PSNR(3DFSRCNN):\", pg)\n",
    "print(\"Min PSNR(3DFSRCNN):\", minp)\n",
    "print()\n",
    "print(\"Max SSIM(3DFSRCNN):\", maxs)\n",
    "print(\"Average SSIM(3DFSRCNN):\", s)\n",
    "print(\"Min SSIM(3DFSRCNN):\", mins)\n",
    "print()\n",
    "print(\"Average time(second) for each scan:\", timez/len(files))\n",
    "print()"
   ]
  }
 ],
 "metadata": {
  "accelerator": "GPU",
  "colab": {
   "collapsed_sections": [],
   "name": "Testing.ipynb",
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
